# Generated by Django 4.0.4 on 2022-05-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=122)),
                ('user_phone', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=122)),
                ('user_address', models.TextField()),
            ],
        ),
    ]
